var files =
[
    [ "avoid-trouble.h", "avoid-trouble_8h_source.html", null ],
    [ "base.h", "base_8h_source.html", null ],
    [ "build_theolizer.h", "build__theolizer_8h.html", null ],
    [ "core.h", "core_8h_source.html", null ],
    [ "core_assorted.h", "core__assorted_8h_source.html", null ],
    [ "core_serializer.h", "core__serializer_8h_source.html", null ],
    [ "core_switcher.h", "core__switcher_8h_source.html", null ],
    [ "core_type_info.h", "core__type__info_8h_source.html", null ],
    [ "external.h", "external_8h_source.html", null ],
    [ "internal.h", "internal_8h_source.html", null ],
    [ "list.h", "list_8h_source.html", null ],
    [ "mainpage.h", "mainpage_8h.html", null ],
    [ "memory.h", "memory_8h_source.html", null ],
    [ "prepare.h", "prepare_8h.html", null ],
    [ "program.h", "program_8h.html", null ],
    [ "project.h", "project_8h_source.html", null ],
    [ "rbfor.h", "rbfor_8h_source.html", null ],
    [ "reference.h", "reference_8h.html", null ],
    [ "report.h", "report_8h_source.html", null ],
    [ "serializer.h", "serializer_8h_source.html", null ],
    [ "serializer_binary.h", "serializer__binary_8h_source.html", null ],
    [ "serializer_fast.h", "serializer__fast_8h_source.html", null ],
    [ "serializer_json.h", "serializer__json_8h_source.html", null ],
    [ "specification.h", "specification_8h.html", null ],
    [ "test_tool.h", "test__tool_8h_source.html", null ],
    [ "u8string.h", "u8string_8h.html", "u8string_8h" ],
    [ "vector.h", "vector_8h_source.html", null ],
    [ "version.h", "version_8h_source.html", null ],
    [ "version_array.h", "version__array_8h_source.html", null ]
];