var files =
[
    [ "1.mainpage.h", "1_8mainpage_8h.html", null ],
    [ "2.specification.h", "2_8specification_8h.html", null ],
    [ "3.prepare.h", "3_8prepare_8h.html", null ],
    [ "4.project.h", "4_8project_8h.html", null ],
    [ "5.build_theolizer.h", "5_8build__theolizer_8h.html", null ],
    [ "6.usage_total.h", "6_8usage__total_8h.html", null ],
    [ "7.usage_individual.h", "7_8usage__individual_8h.html", null ],
    [ "7a.ClassVariation.h", "7a_8_class_variation_8h.html", null ],
    [ "8.reference.h", "8_8reference_8h.html", null ],
    [ "avoid-trouble.h", "avoid-trouble_8h_source.html", null ],
    [ "base.h", "base_8h_source.html", null ],
    [ "core.h", "core_8h_source.html", null ],
    [ "core_assorted.h", "core__assorted_8h.html", "core__assorted_8h" ],
    [ "core_serializer.h", "core__serializer_8h_source.html", null ],
    [ "core_switcher.h", "core__switcher_8h_source.html", null ],
    [ "core_type_info.h", "core__type__info_8h_source.html", null ],
    [ "external.h", "external_8h_source.html", null ],
    [ "internal.h", "internal_8h_source.html", null ],
    [ "list.h", "list_8h_source.html", null ],
    [ "memory.h", "memory_8h_source.html", null ],
    [ "rbfor.h", "rbfor_8h_source.html", null ],
    [ "report.h", "report_8h.html", "report_8h" ],
    [ "serializer.h", "serializer_8h_source.html", null ],
    [ "serializer_binary.h", "serializer__binary_8h_source.html", null ],
    [ "serializer_fast.h", "serializer__fast_8h_source.html", null ],
    [ "serializer_json.h", "serializer__json_8h.html", "serializer__json_8h" ],
    [ "test_tool.h", "test__tool_8h.html", "test__tool_8h" ],
    [ "u8string.h", "u8string_8h.html", "u8string_8h" ],
    [ "vector.h", "vector_8h_source.html", null ],
    [ "version.h", "version_8h.html", "version_8h" ],
    [ "version_array.h", "version__array_8h_source.html", null ]
];