#!/bin/sh

echo "" >> $1

cmake -P source/dirty_check.cmake

if [ "$?" -ne 0 ];
then
    echo "******************************************************************" >> $1
    echo "Sources are dirty.  Please build TheolizerDriver and TheolizerLib." >> $1
    echo "******************************************************************" >> $1
else
    echo "----------------- MD5 Hash Values -----------------" >> $1
    echo -n "TheolizerDriver  : " >> $1
    if [ -e source/driver/version.h ]; then
        grep -h "SourcesHash\[\]" source/driver/version.h                     | sed -e 's/^.*=\"//g' | sed -e 's/\";//g' >> $1
    else
        echo "no version.h" >> $1
    fi

    echo -n "TheolizerLibrary : " >> $1
    if [ -e source/library/theolizer/internal/version.h ]; then
        grep -h "SourcesHash\[\]" source/library/theolizer/internal/version.h | sed -e 's/^.*=\"//g' | sed -e 's/\";//g' >> $1
        echo -n "Library's Header : " >> $1
        grep -h "LibraryHash\[\]" source/library/theolizer/internal/version.h | sed -e 's/^.*=\"//g' | sed -e 's/\";//g' >> $1
    else
        echo "no version.h" >> $1
    fi
fi
cat $1
